### ISSUE TITLE
No such file or directory: 'minecraft-data/data/dataPaths.json'

### ISSUE THREAD

**Issue by NickAnastasoff** [EnzoPB/mc-protocol-minimal#1]
Hi! I tried running your program, but it looks like I need dataPaths.json. Any recommendations on what to put there?
File "/Users/nickanastasoff/miniconda3/lib/python3.11/site-packages/minecraft_data/tools.py", line 7, in convert
    with open(os.path.join(_dir, 'dataPaths.json')) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'minecraft-data/data/dataPaths.json'

**Comment by EnzoPB** [comment]
Hi,
You have to clone the [minecraft-data](https://github.com/PrismarineJS/minecraft-data) repository into the project folder.
The folder structure should look like this:
- minecraft/
- **minecraft-data/**
- main.py

I will add a README file today to explain this a little better

**Comment by NickAnastasoff** [comment]
thanks so much!

edit: wow just tried it out, this works great!
